FROM exercise3.07:1.0.0

ARG GIT_COMMIT=unknown
LABEL git-commit=$GIT_COMMIT

CMD ["mkdir", "-p", "/var/www/html/"]

WORKDIR /var/www/html/

COPY VERSION Dockerfile /var/www/html/
RUN cat Dockerfile

