name: exercise5-01
services:

  init:
    build:
      context: ./init
    volumes:
      - static:/data

  server:
    image: nginx:1.25.3-alpine
    volumes:
      - static:/usr/share/nginx/html
    ports:
      - '127.0.0.1:8080:80'
volumes:
  static:
