name: exercise5-03
services:
  clean:
    image: busybox:1.37.0-glibc
    volumes:
      - static:/static
    command: "rm -rf /static/index.html"

  init:
    image: busybox:1.37.0-glibc
    depends_on:
      - "clean"
    volumes:
      - static:/static
    command: "sh -c 'echo This is from init container. >> /static/index.html'"

  pre:
    image: busybox:1.37.0-glibc
    depends_on:
      - "init"
    volumes:
      - static:/static
    command: "sh -c 'echo This is from pre container. >> /static/index.html'"

  server:
    image: nginx:1.25.3-alpine
    depends_on:
      - "pre"
    volumes:
      - static:/usr/share/nginx/html
    ports:
      - '127.0.0.1:8080:80'

volumes:
  static:
