# Use root/example as user/password credentials
name: exercise7-04

services:
  adminer:
    image: adminer:5.4.2
    ports:
      - '127.0.0.1:8080:8080'
    restart: always

  db:
    image: mysql:8.0.45-debian
    environment:
      MYSQL_ROOT_PASSWORD: example
    command: --default-authentication-plugin=mysql_native_password
    restart: always
