name: activity5-01
services:
  database:
    image: mysql:8.0.45-debian
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always

  wordpress:
    image: wordpress:6.9.1-apache
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db
    ports:
      - '127.0.0.1:9090:80'
    restart: always

volumes:
  data: {}
