name: activity5-02
services:
  db:
    image: postgres:18.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=docker

  nginx:
    image: packtworkshops/the-docker-workshop:chapter5-pta-nginx
    depends_on:
      - web
    volumes:
      - static_data:/service/static
    ports:
      - '0.0.0.0:8080:80'

  web:
    image: packtworkshops/the-docker-workshop:chapter5-pta-web
    depends_on:
      - db
    volumes:
      - static_data:/service/static

volumes:
  db_data:
  static_data:
